export const yakuName = {
  Tsumo: '门清自摸',
  Pinhu: '平和',
  Tanyao: '断幺',
  Ipe: '一杯口',
  SelfWind: '自风',
  RoundWind: '场风',
  Haku: '白',
  Hatsu: '发',
  Chun: '中',
  Sanshoku: '三色同顺',
  Ittsu: '一气通贯',
  Chanta: '混全带幺九',
  Chitoi: '七对子',
  Toitoi: '对对和',
  Sananko: '三暗刻',
  Honroto: '混老头',
  Sandoko: '三色同刻',
  Sankantsu: '三杠子',
  Shosangen: '小三元',
  Honitsu: '混一色',
  Junchan: '纯全带幺九',
  Ryanpe: '两杯口',
  Chinitsu: '清一色',
  Richi: '立直',
  Ippatsu: '一发',
  Rinshan: '岭上开花',
  Chankan: '枪杠',
  Haitei: '海底捞月',
  Houtei: '河底捞鱼',
  WRichi: '两立直',
  Tenhou: '天和',
  Chihou: '地和',
  Kokushi: '国士无双',
  Suanko: '四暗刻',
  Daisangen: '大三元',
  Tsuiso: '字一色',
  Shousushi: '小四喜',
  Lyuiso: '绿一色',
  Chinroto: '清老头',
  Sukantsu: '四杠子',
  Churen: '九莲宝灯',
  Daisushi: '大四喜',
  ChurenNineWaiting: '纯正九莲宝灯',
  SuankoTanki: '四暗刻单骑',
  KokushiThirteenWaiting: '国士无双十三面'
}

export const doubleTimesYakuman = [
  'Daisushi', 'ChurenNineWaiting', 'SuankoTanki', 'KokushiThirteenWaiting'
]
